### ISSUE TITLE
ui的图标用像素字体会不会更好

### ISSUE THREAD

**Issue by Autuamn** [ShaBaiTianCN/FTB-StoneBlock-3#5]
像这样
字体是Unifont
![屏幕截图(19)](https://user-images.githubusercontent.com/35159351/200125336-1a37ef56-c16d-433f-9714-e5363d7731e1.png)

**Comment by AnzhiZhang** [comment]
这个是找了近似原字体的字体。并且由于需要公开发布，筛选了免费可商用的字体
